### ISSUE TITLE
Device Onboarding 1.1.2 issues / questions

### ISSUE THREAD

**Issue by ieneicsongorattila22** [nautobot/nautobot-plugin-device-onboarding#103]
Nautobot v1.5.13
Device Onboarding 1.1.2 ( latest relase ) (  Aug 1, 2022 ) 

Hello,

I have a few questions / issues related to the Device Onboarding plugin.
Your help is appreciated.

1. Is Device Onboarding discontinued? Asking as latest release is almost one year old.

2. Is Cisco Catalyst WLC OS support for Onboarding ( special Napalm driver ) possible somehow? Regardless of model I get the same error for anything inbetween includded Cisco AIR-CT2504-K9 - Cisco AIR-CT2504-K9 .
OnboardException: fail-general: Onboarding for Platform cisco_wlc not supported, as it has no specified NAPALM driver

3. How can multiple credinteals be specified for the case where on some network devices we have other set of SSH credinteals? Authentication should still be attempted with first set of credinteals; if it fails then with the second set.
From my understanding of the code as it is now; this is not possible.  Please help in clarification whether this can be possible with a minor code change.

Thank you.

**Comment by bryanculver** [comment]
@ieneicsongorattila22 I moved this set of question over to the Device Onboarding repo to hopefully address your question. I belive one of the maintainers here @nautobot/plugin-device-onboarding should be able to help.

**Comment by scetron** [comment]
Hello ieneicsongorattila22! Thanks for your questions. We're working on the latest release now and some future, larger updates.

1.  We're working on a minor update right now, just had a mix of upstream and test issues, but should be release very soon. We're also working on some more major updates including Nautobot 2.0 support as well as other things.
2. For adding custom/community drivers:
     - You should be able to add the napalm community driver to the virtual env
     - specify that napalm driver for the platform in Nautobot
     - specify the platform when adding the onboarding task
3. For multiple credentials, there is currently no way to do this on a single onboarding task; however, you can monitor onboarding tasks for credential failure errors and add a new onboarding task with the second set of credentials. It should not be too difficult to add this into the plugin, however it is even easier to write a python script that does this for you.

**Comment by scetron** [comment]
@ieneicsongorattila22  Do you have anymore questions or issues? If not, I'll go ahead and close this issue.

**Comment by ieneicsongorattila22** [comment]
Please close. Thank you for the prompt response.
