### ISSUE TITLE
Nautobot 2.X Device Onboarding failures

### ISSUE THREAD

**Issue by fordjes76** [nautobot/nautobot-plugin-device-onboarding#117]
### Environment
* Nautobot version 2.0.2 (Docker tag too if applicable):
* Python version: 3.11
* Database platform, version: MySQL
* Middleware(s):Device Onboarding Application

### Steps to Reproduce
1. Create a csv with a large list of devices to import, at least 10 devices.
2. Using the import feature of the device onboarding app copy and paste at least 10 devices into the import function.

### Expected Behavior
Nautobot device onboarding app should iterate over each device in the list uploaded through the import function. Adding the devices it is able to successfully connect to and gather data from to the device inventory. 

### Observed Behavior
Nautobot will attempt to load the last device in the list, if it recognizes the device type it will gather all data, add the device then stop iterating over the list. If Nautobot fails to recognize the device type it will fail and not attempt to iterate over any other devices.  I have been able to recreate this will varying numbers of devices added to the import process with no clear indications of the failure cause. 
[Nautobot_Failed_Device_Import_Logs_20231018.txt](https://github.com/nautobot/nautobot/files/13032850/Nautobot_Failed_Device_Import_Logs_20231018.txt)
[Nautobot_Failed_Device_Import_Logs_20231018.txt](https://github.com/nautobot/nautobot/files/13032851/Nautobot_Failed_Device_Import_Logs_20231018.txt)

**Comment by scetron** [comment]
Thanks @fordjes76 for raising the issue. Do you have any custom settings defined for device onboarding in your `nautobot_config.py?`

**Comment by fordjes76** [comment]
Nothing custom at this time, everything is default in our app deployment. I have been able to build Nautobot on Ubuntu 22.04 with Postgres DB with the onboarding APP with the problem remaining. I first found it on Rhel 8 with Postgres DB when I opened the bug.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>


Asurion_Internal_Use_Only

________________________________

**Comment by scetron** [comment]
@fordjes76 Thank you. And one last question, is it possible to provide a sample from the CSV that you have used or provide the column headers you are using in the CSV?

**Comment by fordjes76** [comment]
Sure, if it helps we can hop on a Zoom to see in real-time.  We have an NDA with NTC in place already.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>


Asurion_Internal_Use_Only

________________________________

**Comment by fordjes76** [comment]
Here is the basic structure of the CSV used, sanitized the username and password.

location,ip_address,username,password,port
APN,10.18.32.103,username,password,22
APN,10.18.32.104,username,password,22
APN,10.18.32.105,username,password,22
APN,10.18.32.106,username,password,22
APN,10.18.32.118,username,password,22
APN,10.18.32.117,username,password,22
APN,10.18.0.23,username,password,22
APN,10.18.0.24,username,password,22
APN,10.18.32.76,username,password,22
APN,10.18.32.77,username,password,22


Jesse Ford
Sr Engineer, Network Services
***@***.******@***.***>
voice 615.417.8655



Asurion_Internal_Use_Only

**Comment by fordjes76** [comment]
It should be noted that this is the same structure used on previous 1.X version of Nautobot and apps.

Jesse Ford
Sr Engineer, Network Services
***@***.******@***.***>
voice 615.417.8655



Asurion_Internal_Use_Only

**Comment by svestenik** [comment]
Same issue is happening to me on fresh install Nautobot v2.0.3 instance.
Loaded ~20 IP addresses via import function into Onboarding plugin, last one failed due to device being unreachable and Onboarding plugin just stopped iterrating over all other, without any error shown.
One thing that of notice is that Onboarding plugin seems incapable of listing sites already defined in Nautobot.

Nautobot v2.0.3
Onboarding plugin v2.0.2

As noted by @fordjes76 same import on Nautobot v1.6 works without issues.

Structure of attempted import:

location,ip_address,username,password
somesite,somerange,someuser,somepass
somesite,somerange,someuser,somepass
somesite,somerange,someuser,somepass
somesite,somerange,someuser,somepass
somesite,somerange,someuser,somepass
somesite,somerange,someuser,somepass
somesite,somerange,someuser,somepass
somesite,somerange,someuser,somepass
somesite,somerange,someuser,somepass
somesite,somerange,someuser,somepass
somesite,somerange,someuser,somepass
somesite,somerange,someuser,somepass
somesite,somerange,someuser,somepass
somesite,somerange,someuser,somepass
somesite,somerange,someuser,somepass

**Comment by fordjes76** [comment]
Interesting item as well that we found is that through the API we can access the Onboarding module and load large quantities of devices without issue. So the next question would be what is different between the UI methods and the API methods for using the onboarding tool?

Jesse Ford
Sr Engineer, Network Services




Asurion_Internal_Use_Only

**Comment by svestenik** [comment]
> Interesting item as well that we found is that through the API we can access the Onboarding module and load large quantities of >devices without issue. So the next question would be what is different between the UI methods and the API methods for using the >onboarding tool? 

Confirm, API method works for me also. Managed to onboard 50 devices in succession via API.

**Comment by scetron** [comment]
Thanks for the inputs. I will be taking a closer look at this, this week. I believe that the CSV method should be utilizing the API, but will have to check exactly why 1 failed job is causing all of them to fail. I haven't had luck recreating it, but a code review might turn something up.
