### ISSUE TITLE
drf_spectacular complaint during startup

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot-plugin-device-onboarding#119]
### Environment
* Python version:  
* Nautobot version:  2.0.3
* nautobot-device-onboarding version:  2.0.x

### Steps to Reproduce
1. Install device-onboarding app and start Nautobot

### Observed Behavior

```
 ?: (drf_spectacular.W001) /opt/nautobot/.local/lib/python3.11/site-packages/nautobot_device_onboarding/filters.py: Warning [OnboardingTaskViewSet > OnboardingTaskFilterSet]: Unable to guess choice types from values, filter method's type hint or find "location" in model. Defaulting to string.
```

This is complaining because `location` is not a model field on `OnboardingTask` and drf-spectacular isn't able to infer what type of field this filter field is.

Likely the fix is to `from drf_spectacular.utils import extend_schema_field` and add an `@extend_schema_field({"type": "string"})` annotation to the `location` field on the `OnboardingTaskFilterSet`, but please verify that this is the correct type for this field.

**Comment by scetron** [comment]
Thanks @glennmatthews. This has to be a new install of the plugin? Also, location is a foreign key field on [OnboardingTask](https://github.com/nautobot/nautobot-plugin-device-onboarding/blob/3897b11ea4213bc44945369f758b8dbe592a6558/nautobot_device_onboarding/models.py#L52)

**Comment by glennmatthews** [comment]
I may have been wrong about the root cause then. :-) Taking a second look, I think the issue may be here:

https://github.com/nautobot/nautobot-plugin-device-onboarding/blob/develop/nautobot_device_onboarding/filters.py#L22-L26

Compare the `location` filter definition against the `platform` and `role`  filter definitions below.

```python
    location = django_filters.ModelMultipleChoiceFilter(
        field_name="name",    # perhaps should be "location__name"?
        queryset=Location.objects.all(),
        label="Location (name)",  # perhaps should add 'to_field_name="name"'?
    )
```

**Comment by scetron** [comment]
Likely fixed by using a job instead of filters, models, etc.
