### ISSUE TITLE
Ordering of onboarding tasks in the tasks list view

### ISSUE THREAD

**Issue by anirudhkamath** [nautobot/nautobot-plugin-device-onboarding#22]
### Environment
* Nautobot version:  1.0.3
* nautobot-device-onboarding version:  1.1.0

In the onboarding tasks list view, the onboarding tasks are currently being ordered in decreasing order of the ID of the task by default. Instead, it would be easier to consume the tasks as they run when the tasks are ordered by the date/time they were created on.

### Proposed Functionality

Ordering the onboarding tasks in the task list view in chronological order instead of decreasing order of task IDs

### Use Case

It would be easier to follow the tasks in the list by seeing the latest task run at the top, instead of having to find the exact task(s) run by finding it in the list which is ordered in the decreasing order of the ID, which is not a field the user has any control over.

**Comment by mzbroch** [comment]
### Proposed Solution
Add a new AutoField into the model named `label` that will store the automatically increased positive and unique integer. This will represent a human-friendly integer to allow an easier identification of a given task. This will also allow for sorting.

Scope:
- model change
- table view change
- show the `label` inside detailed task view
(*) Assigning the label for already existing tasks is not in the scope

Tests to be performed:
- existing tasks in the database
- sorting

/cc @dgarros @glennmatthews

**Comment by mzbroch** [comment]
Closed by #23
