### ISSUE TITLE
Error list index out of range 

### ISSUE THREAD

**Issue by zaitochi** [nautobot/nautobot-plugin-device-onboarding#30]
### Environment
* Python version:  3.8
* Nautobot version:  1.1.6
* nautobot-device-onboarding version:  last

### Steps to Reproduce
1. Add Aruba napalm platform 
2. Select the platform in device onboarding
3. Add the device 

### Expected Behavior
Need to retrieve information from aruba device because I have a majority switch with arubaOS 

### Observed Behavior

Nothing, just a failed with message : List index out of range

**Comment by scetron** [comment]
Hello @zaitochi, are you still having trouble with this issue?
