### ISSUE TITLE
unable to onbord NXOS devices 

### ISSUE THREAD

**Issue by nabapal** [nautobot/nautobot-plugin-device-onboarding#32]
### Environment
* Python version:  <3.9 -->
* Nautobot version:  <v1.2.8 -->
* nautobot-device-onboarding version:  

Device should successfully onboard 

getting below error 

celery_worker_1    | 12:15:08.781 INFO    rq.worker :
celery_worker_1    |   INFO guessed device type: cisco_nxos
celery_worker_1    | [2022-04-20 12:15:08,781: INFO/ForkPoolWorker-6] INFO guessed device type: cisco_nxos
celery_worker_1    | 12:15:08.781 INFO    rq.worker :
celery_worker_1    |   Guessed Netmiko Device Type: cisco_nxos
celery_worker_1    | [2022-04-20 12:15:08,781: INFO/ForkPoolWorker-6] Guessed Netmiko Device Type: cisco_nxos
celery_worker_1    | 12:15:13.695 INFO    rq.worker :
celery_worker_1    |   COLLECT: device facts
celery_worker_1    | [2022-04-20 12:15:13,695: INFO/ForkPoolWorker-6] COLLECT: device facts
celery_worker_1    | 12:15:15.567 ERROR   rq.worker :
celery_worker_1    |   OnboardException: fail-general: 'str' object has no attribute 'get'
celery_worker_1    | [2022-04-20 12:15:15,567: ERROR/ForkPoolWorker-6] OnboardException: fail-general: 'str' object has no attribute 'get'

**Comment by scetron** [comment]
Hello @nabapal, I am wondering if you have tried this recently or hit this issue since then? I have successfully onboarded NXOS devices with recent versions.

**Comment by scetron** [comment]
Hello @nabapal, will close for now since I cannot reproduce the issue. Please feel free to open a new issue or reopen this one if you run into trouble.
