### ISSUE TITLE
Tasks do not complete on docker-compose version (with ldap)

### ISSUE THREAD

**Issue by itheodoridis** [nautobot/nautobot-plugin-device-onboarding#48]
### Environment
* Python version:  3.10.6
* Nautobot version:  1.4.1 
* nautobot-device-onboarding version:  1.1.2

### Steps to Reproduce
1. Clone [nautobot-docker-compose](https://github.com/nautobot/nautobot-docker-compose) and adapt files for ldap as well
2. Follow process to create the docker image, launch with docker compose up -d
3. Create new onboarding task for networking device accessible via the nautobot containers and docker host (device config shows up in the config tab)

### Expected Behavior
Onboarding task completes succesfuly, device, platform, etc added.

### Observed Behavior
Onboarding task never completes. When inspecting the log this is the main error message:
nautobot-docker-celery_worker-1    | [2022-08-26 16:45:45,246: ERROR/MainProcess] Received unregistered task of type 'nautobot_device_onboarding.worker.onboard_device_worker'.
nautobot-docker-celery_worker-1    | The message has been ignored and discarded.
nautobot-docker-celery_worker-1    |
nautobot-docker-celery_worker-1    | Did you remember to import the module containing this task?
nautobot-docker-celery_worker-1    | Or maybe you're using relative imports?
nautobot-docker-celery_worker-1    |
nautobot-docker-celery_worker-1    | Please see
nautobot-docker-celery_worker-1    | http://docs.celeryq.org/en/latest/internals/protocol.html
nautobot-docker-celery_worker-1    | for more information.

Please let me know if you need more information.

**Comment by glennmatthews** [comment]
Can you confirm that the Celery worker(s) have the plugin installed and enabled?

**Comment by itheodoridis** [comment]
Hi Glen. Sorry, I have not confirmed that, nor did I know how to. 
However I have spent a few days on this and it wasn't the plugin's fault. 
In the scenario where we run Nautobot with Docker compose, the containers that are derived from the nautobot image all need to have the same copy of the nautobot_config.py file. 
Apparently that was not the case. Either by loading the nautobot_config.py as a volume on all of them or by copying the file over during the image creation process (I was using the process described in the https://github.com/nautobot/nautobot-docker-compose repo for LDAP support) then the plugin would proceed with the onboarding task without errors.
I kind-of perfected the setup making it so that the ownership of the file remains with nautbot:nautobot (user:group) when copied inside the custom image, but there are still issues with the docker-compose schema and configuration.
However I believe that these should be raised as issues/discussion in that repo as well as the slack channel for nautobot and not here.
I would be grateful for advice on how to check if the workers have the plugin installed but other than that, this issue should be closed.

**Comment by itheodoridis** [comment]
Again to clarify: this happens because the workers containers did not get access to the same copy of nautobot_config.py .
I will detail here the two methods to solve this (you can use both if you want but you will be negating the benefit each one offers:
1. Make sure you load the file both for the main nautobot container and all the worker containers (beat too if you have it) as a volume:
```
    volumes:
      - "./nautobot_config.py:/opt/nautobot/nautobot_config.py"
```
This way you don't have to modify the custom image every time you change the config (it shouldn't happen too often though).
2. Copy over the nautobot_config.py file during the custom image creation process, here is an example Dockerfile:
```
ARG PYTHON_VER=3.10
ARG NAUTOBOT_VERSION=1.4.2

FROM networktocode/nautobot:${NAUTOBOT_VERSION}-py${PYTHON_VER} as base

USER 0
RUN apt-get update -y && apt-get install -y libldap2-dev libsasl2-dev libssl-dev

# ---------------------------------
# Stage: Builder
# ---------------------------------
FROM base as builder

RUN apt-get install -y gcc && \
    apt-get autoremove -y && \
    apt-get clean all && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip wheel && pip3 install django-auth-ldap

# ---------------------------------
# Stage: Final
# ---------------------------------
FROM base as final
ARG PYTHON_VER
USER 0

COPY --from=builder /usr/local/lib/python${PYTHON_VER}/site-packages /usr/local/lib/python${PYTHON_VER}/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin
COPY --chown=nautobot:nautobot ./nautobot_config.py /opt/nautobot/nautobot_config.py

USER nautobot

WORKDIR /opt/nautobot

COPY --chown=nautobot:nautobot ./local_requirements.txt /opt/nautobot/
RUN pip install --no-warn-script-location -r /opt/nautobot/local_requirements.txt
COPY --chown=nautobot:nautobot ./plugin_requirements.txt /opt/nautobot/
RUN pip install --no-warn-script-location -r /opt/nautobot/plugin_requirements.txt
```

In this example the nautobot_config.py file is copied inside the container in the final stage by the root user but with proper file ownership (nautobot:nautobot). 
The two other file copies that happen under the nautobot user concern additional python packages (local_requirements.txt) and the plugin packages (plugin_requirements.txt) which are installed in the user space. These could be done in the builder stage and get copied over by the first two commands in the Final stage but I took this approach after https://github.com/nautobot/nautobot-docker-compose/blob/main/docs/plugins.md where the proposed dockerfile does everything with the default user (which in this case is nautobot:nautobot as defined in the official parent image of nautobot)
```
ARG PYTHON_VER
ARG NAUTOBOT_VERSION=1.2.8
FROM networktocode/nautobot:${NAUTOBOT_VERSION}-py${PYTHON_VER}

COPY ./plugin_requirements.txt /opt/nautobot/
RUN pip install --no-warn-script-location -r /opt/nautobot/plugin_requirements.txt

COPY config/nautobot_config.py /opt/nautobot/nautobot_config.py
```
This file can be found here: https://github.com/nautobot/nautobot-docker-compose/blob/main/plugin_example/Dockerfile-Plugins
I am closing the issue at this point.
