### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by itdependsnetworks** [nautobot/nautobot-plugin-device-onboarding#63]
### Environment
* Python version:  3.7
* Nautobot version:  1.5.2
* nautobot-device-onboarding version:  develop branch

### Steps to Reproduce
1. Install with Nautobot 1.5.2
2. Run invoke tests

### Expected Behavior

Passing tests

### Observed Behavior

```
`======================================================================
FAIL: test_list_objects_with_permission (nautobot_device_onboarding.tests.test_views.OnboardingTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/test/utils.py", line 387, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/nautobot/utilities/testing/views.py", line 711, in test_list_objects_with_permission
    self.assertIn(
AssertionError: '<a href="/plugins/device-onboarding/">Onboarding Tasks</a>' not found in '\n\n\n\n<!DOCTYPE html>\n<html lang="en">\n<head>\n    <title>Onboarding Tasks - Nautobot</title>\n    \n\n\n\n    <link rel="stylesheet"\n
<ommited>
```

During this PR in Nautobot: https://github.com/nautobot/nautobot/pull/2841/files#diff-3c2b9c2fd181764da3a3fbbb37c756af1a5eb1ac5b1ec1993378ccafa3a328b4R694 test_list_objects_with_permission was updated. That testing harness is inherited here and is no longer passing

Pinging @HanlinMiao for visibility.

**Comment by HanlinMiao** [comment]
Per discussion with the core team, we think leaving the failing test in but extending it with a more helpful message is the right approach. Because the primary reason why the test is failing is because the plugin's `_list.html` did not extend the generic `object_list.html`. Do you think it's reasonable? @itdependsnetworks
