### ISSUE TITLE
Legacy template needs to extend `generic/object_list.html`

### ISSUE THREAD

**Issue by HanlinMiao** [nautobot/nautobot-plugin-device-onboarding#66]
https://github.com/nautobot/nautobot-plugin-device-onboarding/blob/develop/nautobot_device_onboarding/templates/nautobot_device_onboarding/onboarding_tasks_list.html
needs to be changed to extend `generic/object_list.html`

**Comment by glennmatthews** [comment]
duplicate of #63, fixed by #65.
