### ISSUE TITLE
0003_onboardingtask_label migration is not reversible

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot-plugin-device-onboarding#70]
### Environment
* Python version:  
* Nautobot version:  1.5.8
* nautobot-device-onboarding version:  1.1.2

### Steps to Reproduce
1. Install nautobot-device-onboarding app and enable it in Nautobot
2. As preparation for uninstalling the app as no longer needed, attempt to remove its database tables by running `nautobot-server migrate nautobot_device_onboarding zero`

### Expected Behavior

Migrations to be rolled back, resulting in the removal of all device-onboarding tables from the database.

### Observed Behavior

```
django.db.migrations.exceptions.IrreversibleError: Operation <RunPython <function create_labels_for_existing_tasks at 0x7f88cfe0c170>> in nautobot_device_onboarding.0003_onboardingtask_label is not reversible
```

**Comment by mzbroch** [comment]
This was a data migration, where a label of type INTeger was introduced to allow human sorting.

Just to clarify - what should be the "expected behaviour":
- allow to zeroize all the tables of onboarding plugin
- or just reverse 0003 (reverse data migration, drop the label column) ?

**Comment by glennmatthews** [comment]
The ultimate goal would be to let it migrate all the way back to zero as a way to clean up before uninstalling the app. If there's an alternate way to support this rather than making the migrations reversible, I'm open to that, but let's try to come up with a standard solution that we can document everywhere.
