### ISSUE TITLE
Prometheus metrics for onboard device

### ISSUE THREAD

**Issue by davidban77** [nautobot/nautobot-plugin-device-onboarding#86]
### Environment
* Nautobot version:  1.5.13 (to get `metrics.py` support)
* nautobot-plugin-device-onboarding version:  latest

### Proposed Functionality

Expose Prometheus metrics for this app. Examples:

#### Onboard Device Errors

At the moment there is a metric capturing the amount of devices successfully onboard with `onboarding_tasks_results_counter`. This could be augmented with metrics capturing when there are issues:

- `nautobot_device_onboarding_tasks_errors_total{error_code="DeviceIPLookupFailed"} 2.0`

### Use Case

Allow users of the platform to generate time series from their Nautobot instance. In the end this could troubleshoot and get more insight of their Nautobot platform.

**Comment by scetron** [comment]
Closed by #87
