### ISSUE TITLE
Device Onboarding 1.1.2 issues / questions #4001

### ISSUE THREAD

**Issue by ieneicsongorattila22** [nautobot/nautobot-plugin-device-onboarding#95]
Nautobot v1.5.13
Device Onboarding 1.1.2 ( latest relase ) (  Aug 1, 2022 ) 

Hello,

I have a few questions / issues related to the Device Onboarding plugin.
Your help is appreciated.

1. Is Device Onboarding discontinued? Asking as latest release is almost one year old.

2. Is Cisco Catalyst WLC OS support for Onboarding ( special Napalm driver ) possible somehow? Regardless of model I get the same error for anything inbetween includded Cisco AIR-CT2504-K9 - Cisco AIR-CT2504-K9 .
OnboardException: fail-general: Onboarding for Platform cisco_wlc not supported, as it has no specified NAPALM driver

3. How can multiple credinteals be specified for the case where on some network devices we have other set of SSH credinteals? Authentication should still be attempted with first set of credinteals; if it fails then with the second set.
From my understanding of the code as it is now; this is not possible.  Please help in clarification whether this can be possible with a minor code change.

Thank you.

**Comment by jvanderaa** [comment]
1) No, things have been working as expected in most of the development needs I would say
2) Some more things coming on the WLC support
3) I have typically run the first set of jobs, then run a second instance of the job with the alternate credentials.

**Comment by ieneicsongorattila22** [comment]
> 1. No, things have been working as expected in most of the development needs I would say
> 2. Some more things coming on the WLC support
> 3. I have typically run the first set of jobs, then run a second instance of the job with the alternate credentials.

Thank you for the prompt update.

Regards 3 ; second instance of the job. 

So in the first instance you use the default credinteals from nautobot_config.py ; and for the second you specify username/password in CSV/payload.
This is sound; or is there a more elegant solution that I'm missing?

**Comment by scetron** [comment]
Hello @ieneicsongorattila22, does this help clarify your questions? Do you need any other assitance?
